@BASE_URL = http://localhost:8000

### Get all notes
GET {{BASE_URL}}/api/notes
Accept: application/json

### Get single note
GET {{BASE_URL}}/api/notes/16
Accept: application/json

### Delete single note by id
DELETE {{BASE_URL}}/api/notes/4
Accept: application/json

### Store new note
POST {{BASE_URL}}/api/notes
Accept: application/json
Content-Type: application/json

{
    "title": "Test create via http 1"
}

### Update existing note (single)
PUT {{BASE_URL}}/api/notes/16
Accept: application/json
Content-Type: application/json

{
    "title": "Update title",
    "body": "update body"
}
